apiVersion: v1
kind: Pod
metadata:
  name: hello-minikube
  labels:
    app: hello
    environment: learning
spec:
  containers:
  - name: nginx
    image: nginx:1.25-alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
